package apidrift

import (
	"fmt"
	"strings"
	"time"
)

// Report renders the check as the body of the tracking issue.
func Report(r Result, notes []Announcement, since time.Time, now time.Time) string {
	var b strings.Builder
	fmt.Fprintf(&b, "Weekly comparison of the fields this provider decodes against Anthropic's API reference, run %s.\n\n",
		now.UTC().Format("2006-01-02"))

	if len(r.Findings) == 0 && len(notes) == 0 {
		b.WriteString("Nothing to act on.\n")
	}

	if len(r.Findings) > 0 {
		b.WriteString("## Deprecated fields the client still depends on\n\n")
		b.WriteString("Each of these reads back empty on the day the API stops sending it.\n\n")
		b.WriteString("| Client type | Field | Use instead | Reference |\n|---|---|---|---|\n")
		for _, f := range r.Findings {
			repl := "`" + f.Replacement + "`"
			if f.Kind == KindNoReplacement {
				repl = "none named: stop reading it"
			}
			fmt.Fprintf(&b, "| `%s` | `%s` | %s | [%s](https://platform.claude.com/docs/en/api/%s) |\n", f.Type, f.Path, repl, f.Page, f.Page)
		}
		b.WriteString("\nWhat the reference says:\n\n")
		for _, f := range r.Findings {
			fmt.Fprintf(&b, "- `%s.%s`: %s\n", f.Type, f.Field, f.Note)
		}
		b.WriteString("\nThe usual fix decodes both names and prefers the new one, as `RBACGroup.EffectiveRoleIDs` does.\n\n")
	}

	if len(notes) > 0 {
		fmt.Fprintf(&b, "## Release notes since %s worth reading\n\n", since.Format("2006-01-02"))
		b.WriteString("Changes announced in prose rather than on a field, such as a retired scope or a changed default. ")
		b.WriteString("These are matched by keyword, so some will not affect this provider.\n\n")
		for _, n := range notes {
			fmt.Fprintf(&b, "- **%s**: %s\n", n.Date.Format("2006-01-02"), n.Text)
		}
		b.WriteString("\n")
	}

	if len(r.Fallbacks) > 0 {
		b.WriteString("<details><summary>Deprecated fields read only as a fallback (")
		fmt.Fprintf(&b, "%d)</summary>\n\n", len(r.Fallbacks))
		b.WriteString("Safe today. The fallback can be removed once the API stops sending the old field.\n\n")
		for _, f := range r.Fallbacks {
			fmt.Fprintf(&b, "- `%s.%s` → `%s`\n", f.Type, f.Field, f.Replacement)
		}
		b.WriteString("\n</details>\n\n")
	}

	if len(r.UnusedIgnores) > 0 {
		b.WriteString("<details><summary>Ignore entries that no longer match anything</summary>\n\n")
		for _, ig := range r.UnusedIgnores {
			fmt.Fprintf(&b, "- `%s.%s`: remove it from `internal/apidrift/manifest.json`\n", ig.Type, ig.Field)
		}
		b.WriteString("\n</details>\n\n")
	}

	if len(r.Unchecked) > 0 {
		fmt.Fprintf(&b, "<details><summary>Client types no reference page reaches (%d)</summary>\n\n", len(r.Unchecked))
		b.WriteString("A deprecation in one of these would go unnoticed. Map it in `internal/apidrift/manifest.json` if it holds response data.\n\n")
		b.WriteString("`" + strings.Join(r.Unchecked, "`, `") + "`\n\n</details>\n\n")
	}

	b.WriteString("---\nGenerated by `.github/workflows/api-drift.yml`. See CONTRIBUTING.md, *Keeping up with API changes*.\n")
	return b.String()
}
